### ISSUE TITLE
Help in macOS builds

### ISSUE THREAD

**Issue by amirhakimnejad** [MatsuriDayo/nekoray#350]
Hello,
Thank you for the great client.
I can help with macOS builds and providing .dmg files.
Would you prefer I put the builds here as issues, or should I send them to you? Or should I create a fork and put the builds in my repo releases?

**Comment by omidshojaee** [comment]
Please provide the macos build in any way you can.

**Comment by chromer030** [comment]
Why not via GitHub Actions ?

**Comment by waangcy** [comment]
编译不重要.....重要的是有人能解决macos平台上一些特有的bug...

**Comment by amirhakimnejad** [comment]
> Why not via GitHub Actions ?

Sure, why not. Though I'm not much familiar with it. Can you help?

**Comment by amirhakimnejad** [comment]
> 编译不重要.....重要的是有人能解决macos平台上一些特有的bug...

It sure is, when it comes to users. We should do as much as we can. 
About the bugs, we can take a look at them, too. Are there any priorities?

**Comment by amirhakimnejad** [comment]
> 目前的情况是 actions 10.15 快要淘汰了，而且在 10.15 上编译对新系统的兼容性不好。新系统的适配没有人做。

Ok, we can make some tasks to make it compatible.

**Comment by amirhakimnejad** [comment]
I'm going to fork this for now and put the .dmg s on that repo, since files more than 25MB are not allowed to be attached

**Comment by amirhakimnejad** [comment]
For now I put the manual builds [here](https://github.com/amirhakimnejad/nekoray/releases/)

**Comment by leohougmail** [comment]
> For now I put the manual builds [here](https://github.com/amirhakimnejad/nekoray/releases/)

Can you also make an ARM build for M1/2 chips?

**Comment by amirhakimnejad** [comment]
> 
Sorry for that.
As @arm64v8a mentioned, the client has a problem with macOS 13. We have to improve the client with the data in #281

**Comment by chromer030** [comment]
And for arm64 automated Github Action builds, there is currently no Apple Silicon based Action Runner servers.

**Comment by NeetHuang** [comment]
> > 现在我把手动构建[放在这里](https://github.com/amirhakimnejad/nekoray/releases/)
> 
> 你也可以为M1 / 2芯片制造ARM构建吗？

https://github.com/NeetHuang/nekoray-macos-build/releases/tag/2.15-macos 
This was built by me through the Mac M1.

**Comment by waangcy** [comment]
> > > 现在我把手动构建[放在这里](https://github.com/amirhakimnejad/nekoray/releases/)
> > 
> > 
> > 你也可以为M1 / 2芯片制造ARM构建吗？
> 
> https://github.com/NeetHuang/nekoray-macos-build/releases/tag/2.15-macos This was built by me through the Mac M1.

感谢分享，请问可以持续参与构建吗

**Comment by NazariArmin** [comment]
> > > 现在我把手动构建[放在这里](https://github.com/amirhakimnejad/nekoray/releases/)
> > 
> > 
> > 你也可以为M1 / 2芯片制造ARM构建吗？
> 
> https://github.com/NeetHuang/nekoray-macos-build/releases/tag/2.15-macos This was built by me through the Mac M1.

are you sure it's working?

I was trying to install it on MacBook Air M2 but i got this error:

“nekoray” is damaged and can’t be opened. You should move it to the Trash

**Comment by NeetHuang** [comment]
> > > > 现在我把手动构建[放在这里](https://github.com/amirhakimnejad/nekoray/releases/)
> > > 
> > > 
> > > 你也可以为M1 / 2芯片制造ARM构建吗？
> > 
> > 
> > https://github.com/NeetHuang/nekoray-macos-build/releases/tag/2.15-macos This was built by me through the Mac M1.
> 
> are you sure it's working?
> 
> I was trying to install it on MacBook Air M2 but i got this error:
> 
> “nekoray” is damaged and can’t be opened. You should move it to the Trash

Have you solved this problem? I tested it well on the M1 apple architecture. This problem may be caused by you not allowing third-party applications to run in the security settings of the system.

**Comment by y8d4w1** [comment]
> 

还是一样的，我的M1 Pro，还是说文件损坏，移动到碎纸篓，安全性已经设置为任何来源

**Comment by Saulul** [comment]
@NeetHuang I have the same issue with your Mac m1 build, with the older mac builds on this repo, it would show in privacy settings and I could allow it to run. This one doesn't run at all.
![image](https://user-images.githubusercontent.com/35707165/220355191-75a6bf26-9c0d-4220-a4a6-e265ac8752d3.png)

**Comment by NeetHuang** [comment]
> @NeetHuang I have the same issue with your Mac m1 build, with the older mac builds on this repo, it would show in privacy settings and I could allow it to run. This one doesn't run at all. ![image](https://user-images.githubusercontent.com/35707165/220355191-75a6bf26-9c0d-4220-a4a6-e265ac8752d3.png)
我目前不清楚具体发生原因，但是你可以尝试以下的方法。
`sudo spctl --master-disable`
输入你的密码
然后在隐私和安全设置中开启任何来源
再次尝试打开nekoray

I don't know the specific reason, but you can try the following methods.
`sudo spctl --master-disable`
Enter your password
Then open any source in privacy and security settings
Try to open nekoray again

**Comment by NeetHuang** [comment]
> @NeetHuang I have the same issue with your Mac m1 build, with the older mac builds on this repo, it would show in privacy settings and I could allow it to run. This one doesn't run at all. ![image](https://user-images.githubusercontent.com/35707165/220355191-75a6bf26-9c0d-4220-a4a6-e265ac8752d3.png)

我目前不清楚具体发生原因，但是你可以尝试以下的方法。
`sudo spctl --master-disable`
输入你的密码
然后在隐私和安全设置中开启任何来源
再次尝试打开nekoray
I don't know the specific reason, but you can try the following methods.
`sudo spctl --master-disable`
Enter your password
Then open any source in privacy and security settings
Try to open nekoray again

**Comment by Saulul** [comment]
> > @NeetHuang I have the same issue with your Mac m1 build, with the older mac builds on this repo, it would show in privacy settings and I could allow it to run. This one doesn't run at all. 
> 
> I don't know exactly why it happened, but you can try the following methods. `sudo spctl --master-disable` Enter your password Then open any source in privacy and security settings Try to open nekoray I don't know the specific reason, but you can try the following methods. `sudo spctl --master-disable` Enter your password Then open any source in privacy and security settings Try to open nekoray again

![image](https://user-images.githubusercontent.com/35707165/220360647-66687f62-67fb-485b-a912-f145082d3f7a.png)
I've tried that but still facing the same issue.

**Comment by NeetHuang** [comment]
> > > @NeetHuang I have the same issue with your Mac m1 build, with the older mac builds on this repo, it would show in privacy settings and I could allow it to run. This one doesn't run at all.
> > 
> > 
> > I don't know exactly why it happened, but you can try the following methods. `sudo spctl --master-disable` Enter your password Then open any source in privacy and security settings Try to open nekoray I don't know the specific reason, but you can try the following methods. `sudo spctl --master-disable` Enter your password Then open any source in privacy and security settings Try to open nekoray again
> 
> ![image](https://user-images.githubusercontent.com/35707165/220360647-66687f62-67fb-485b-a912-f145082d3f7a.png) I've tried that but still facing the same issue. Nothing to approve in 'Security & Privacy'.

Do you want to set questions for permissions? Can you try to check the permission settings of the target

**Comment by Saulul** [comment]
@NeetHuang Are you on Mac OS 13+? That could be the issue because I am on 12.6. I will try updating to Ventura some time tonight and check again

**Comment by NeetHuang** [comment]
> @NeetHuang Are you on Mac OS 13+? That could be the issue because I am on 12.6. I will try updating to Ventura some time tonight and check again

正常装入Applications后你需要执行
`xattr -cr /Applications/nekoray.app`
这是由于上传到github后被添加了隐藏的属性，我暂时不清楚如何处理，临时方法请每次下载安装后执行一次命令。

After loading Applications normally, you need to execute
`xattr -cr /Applications/nekoray.app`
This is because hidden attributes have been added after uploading to github. I'm not sure how to handle it. For temporary methods, please execute the command after each download and installation.

**Comment by Saulul** [comment]
> > > 
> > 
> > 
> > Still the same, my M1 Pro, still says the file is corrupt, moved to the trash, security is already set to any source
> 
> Execute the command after installation`xattr -cr /Applications/nekoray.app`

Thank you for replying. I ran `xattr -cr /Applications/nekoray.app` after installing, then tried running nekoray and getting the following error now:
![image](https://user-images.githubusercontent.com/35707165/220372151-76d97c6a-ea32-4667-b144-1870739449c6.png)

**Comment by NeetHuang** [comment]
> > > > 
> > > 
> > > 
> > > Still the same, my M1 Pro, still says the file is corrupt, moved to the trash, security is already set to any source
> > 
> > 
> > Execute the command after installation`xattr -cr /Applications/nekoray.app`
> 
> Thank you for replying. I ran `xattr -cr /Applications/nekoray.app` after installing, then tried running nekoray and getting the following error now: ![image](https://user-images.githubusercontent.com/35707165/220372151-76d97c6a-ea32-4667-b144-1870739449c6.png)

It seems that the original problem has been solved. The new problem may be caused by my compilation on 13.1. I'm sorry that I don't have other versions to verify.

**Comment by Saulul** [comment]
> It seems that the original problem has been solved. The new problem may be caused by my compilation on 13.1. I'm sorry that I don't have other versions to verify.

Yeah no worries, I will try 13.1 and report back

**Comment by omidshojaee** [comment]
The latest build (2.16) still crashes on Intel and Ventura 13.2 with this error:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork
Referenced from: <44C8E2EF-1D22-36B7-97D5-77DA5AC670FE> /Applications/nekoray.app/Contents/MacOS/nekoray
Reason: tried: '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

**Comment by sw19999** [comment]
13.2.1 黑苹果，SIP关闭的，用了xattr命令无效，依旧无法运行，只能一直用2.12版本。不知道为什么作者不想继续发布macOS版本，macOS这边本来梯子软件就少。支持的协议也少。希望能继续编译

**Comment by NeetHuang** [comment]
> 13.2.1 黑苹果，SIP关闭的，用了xattr命令无效，依旧无法运行，只能一直用2.12版本。不知道为什么作者不想继续发布macOS版本，macOS这边本来梯子软件就少。支持的协议也少。希望能继续编译

黑苹果用本页楼主的版本试试，我发布的是苹果芯片M1的。。而且是因为没有开发者证书导致需要xattr，这个问题和你黑苹果无关。

**Comment by omidshojaee** [comment]
Hello @amirhakimnejad 

The original macOS build has a folder "Frameworks" which contains required Qt libraries, but in your macOS builds this folder does not exists, so we get "Library not loaded" error.

**Comment by sw19999** [comment]
> > 13.2.1 黑苹果，SIP关闭的，用了xattr命令无效，依旧无法运行，只能一直用2.12版本。不知道为什么作者不想继续发布macOS版本，macOS这边本来梯子软件就少。支持的协议也少。希望能继续编译
> 
> 黑苹果用本页楼主的版本试试，我发布的是苹果芯片M1的。。而且是因为没有开发者证书导致需要xattr，这个问题和你黑苹果无关。

我回复的就是本页楼主编译的intel版本，跟兄弟编译的m1版本一样无法运行，另一台台式机11.x系统Big Sur都不能运行

**Comment by y8d4w1** [comment]
> The latest build (2.16) still crashes on Intel and Ventura 13.2 with this error:
> 
> ```
> Termination Reason:    Namespace DYLD, Code 1 Library missing
> Library not loaded: /usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork
> Referenced from: <44C8E2EF-1D22-36B7-97D5-77DA5AC670FE> /Applications/nekoray.app/Contents/MacOS/nekoray
> Reason: tried: '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file, not in dyld cache)
> (terminated at launch; ignore backtrace)
> ```

打包的时候没有放QT库进去导致的，我也有同样问题。

**Comment by sw19999** [comment]
> > The latest build (2.16) still crashes on Intel and Ventura 13.2 with this error:
> > ```
> > Termination Reason:    Namespace DYLD, Code 1 Library missing
> > Library not loaded: /usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork
> > Referenced from: <44C8E2EF-1D22-36B7-97D5-77DA5AC670FE> /Applications/nekoray.app/Contents/MacOS/nekoray
> > Reason: tried: '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file, not in dyld cache)
> > (terminated at launch; ignore backtrace)
> > ```
> 
> 打包的时候没有放QT库进去导致的，我也有同样问题。

同意，看报错信息猜测也是运行库的问题，可惜没人编译新版本

**Comment by aaaamirabbas** [comment]
I also agree and have a serious problem.
Please create the correct documentation for compiling.
Or **re-release the Mac version like Windows and Linux.**

Thanks

**Comment by aaaamirabbas** [comment]
**Unofficial release: https://github.com/MatsuriDayo/nekoray/issues/445**

**Comment by NeetHuang** [comment]
> > The latest build (2.16) still crashes on Intel and Ventura 13.2 with this error:
> > ```
> > Termination Reason:    Namespace DYLD, Code 1 Library missing
> > Library not loaded: /usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork
> > Referenced from: <44C8E2EF-1D22-36B7-97D5-77DA5AC670FE> /Applications/nekoray.app/Contents/MacOS/nekoray
> > Reason: tried: '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file, not in dyld cache)
> > (terminated at launch; ignore backtrace)
> > ```
> 
> 打包的时候没有放QT库进去导致的，我也有同样问题。

确实是这个问题，但是单独放进去是不行的，看起来需要对qt5进行静态编译，我和 @amirhakimnejad 出现的问题是一样的，QT5变成了动态链接，需要本机上有QT5的环境而且位置 在/usr/local/opt/qt@5 一致才行，我需要一个新的编译步骤，如果有人知道怎么做请告诉我，当前我也正在进行尝试静态打包qt5库到app里。

**Comment by omidshojaee** [comment]
@aaaamirabbas Doesn't work on Intel Mac Ventura 13.3. VPN Mode is not starting.

**Comment by kvm66** [comment]
对MAC版本要求太高，黑苹果用户表示放弃

**Comment by tdjnodj** [comment]
@kvm66 https://github.com/MatsuriDayo/nekoray/issues/49

**Comment by aaaamirabbas** [comment]
**I have developed a bash script to ‍‍‍‍`automatically` generate a `macOS` version.**
**- https://github.com/aaaamirabbas/nekoray-macos**

**In this repository, you can use scripts to build on your system automatically and use pre-made releases for macOS.**

- Report if you have any problems.
- Please help contribute and improve this script.
- This script is completely automatic and performs the download and builds operations automatically and finally outputs two applications for different processor architectures.

**Comment by amirhakimnejad** [comment]
> **I have developed a bash script to ‍‍‍‍`automatically` generate a `macOS` version.** **- https://github.com/aaaamirabbas/nekoray-macos**
> 
> **In this repository, you can use scripts to build on your system automatically and use pre-made releases for macOS.**
> 
> * Report if you have any problems.
> * Please help contribute and improve this script.
> * This script is completely automatic and performs the download and builds operations automatically and finally outputs two applications for different processor architectures.

Excellent. Does it handle the problem mentioned in the Missing libraries of QT mentioned here?:
https://github.com/MatsuriDayo/nekoray/issues/350#issuecomment-1452275076

@arm64v8a The MacOS build document does not say anything about that either. The app does not start if we don't have qt installed on our system. There should be a document to put qt dependencies within build files.

**Comment by NeetHuang** [comment]
> > **I have developed a bash script to ‍‍‍‍`automatically` generate a `macOS` version.** **- https://github.com/aaaamirabbas/nekoray-macos**
> > **In this repository, you can use scripts to build on your system automatically and use pre-made releases for macOS.**
> > 
> > * Report if you have any problems.
> > * Please help contribute and improve this script.
> > * This script is completely automatic and performs the download and builds operations automatically and finally outputs two applications for different processor architectures.
> 
> Excellent. Does it handle the problem mentioned in the Missing libraries of QT mentioned here?: [#350 (comment)](https://github.com/MatsuriDayo/nekoray/issues/350#issuecomment-1452275076)
> 
> @arm64v8a The MacOS build document does not say anything about that either. The app does not start if we don't have qt installed on our system. There should be a document to put qt dependencies within build files.

关于QT依赖库的问题我已经解决了，已经成功将其静态编译到nekoray中，在无需依赖的环境下正常运行，当前仅限于我编译的M1版本，Intel版本需要@amirhakimnejad  进行编译。
成功解决QT依赖库的关键是需要手动构建qt5的编译，并使其静态化，这样在编译nekoray的时候就会编译到程序当中，带QT5静态编译正确的nekoray程序大小~25MB。
I have solved the problem regarding the QT dependency library. I have successfully compiled it statically into nekoray, and it runs smoothly in an environment without dependencies. Currently, this is only applicable to the M1 version that I compiled, while the Intel version needs to be compiled by @amirhakimnejad.

The key to solving the QT dependency library issue is to manually build the qt5 compiler and make it static. This way, when compiling nekoray, it will be included in the program, resulting in a correctly statically compiled nekoray program with a size of around 25MB.

**Comment by amirhakimnejad** [comment]
> > > **I have developed a bash script to ‍‍‍‍`automatically` generate a `macOS` version.** **- https://github.com/aaaamirabbas/nekoray-macos**
> > > **In this repository, you can use scripts to build on your system automatically and use pre-made releases for macOS.**
> > > 
> > > * Report if you have any problems.
> > > * Please help contribute and improve this script.
> > > * This script is completely automatic and performs the download and builds operations automatically and finally outputs two applications for different processor architectures.
> > 
> > 
> > Excellent. Does it handle the problem mentioned in the Missing libraries of QT mentioned here?: [#350 (comment)](https://github.com/MatsuriDayo/nekoray/issues/350#issuecomment-1452275076)
> > @arm64v8a The MacOS build document does not say anything about that either. The app does not start if we don't have qt installed on our system. There should be a document to put qt dependencies within build files.
> 
> 关于QT依赖库的问题我已经解决了，已经成功将其静态编译到nekoray中，在无需依赖的环境下正常运行，当前仅限于我编译的M1版本，Intel版本需要@amirhakimnejad 进行编译。 成功解决QT依赖库的关键是需要手动构建qt5的编译，并使其静态化，这样在编译nekoray的时候就会编译到程序当中，带QT5静态编译正确的nekoray程序大小~25MB。 I have solved the problem regarding the QT dependency library. I have successfully compiled it statically into nekoray, and it runs smoothly in an environment without dependencies. Currently, this is only applicable to the M1 version that I compiled, while the Intel version needs to be compiled by @amirhakimnejad.
> 
> The key to solving the QT dependency library issue is to manually build the qt5 compiler and make it static. This way, when compiling nekoray, it will be included in the program, resulting in a correctly statically compiled nekoray program with a size of around 25MB.

Is there a document for it? Can you share it with me?

**Comment by aaaamirabbas** [comment]
> > **I have developed a bash script to ‍‍‍‍`automatically` generate a `macOS` version.** **- https://github.com/aaaamirabbas/nekoray-macos**
> > **In this repository, you can use scripts to build on your system automatically and use pre-made releases for macOS.**
> > 
> > * Report if you have any problems.
> > * Please help contribute and improve this script.
> > * This script is completely automatic and performs the download and builds operations automatically and finally outputs two applications for different processor architectures.
> 
> Excellent. Does it handle the problem mentioned in the Missing libraries of QT mentioned here?: [#350 (comment)](https://github.com/MatsuriDayo/nekoray/issues/350#issuecomment-1452275076)
> 
> @arm64v8a The MacOS build document does not say anything about that either. The app does not start if we don't have qt installed on our system. There should be a document to put qt dependencies within build files.

I examined the QT problem and **solved** it before.
In fact, the required QT libraries in this script are attached to the output app.

You can get and test the latest released version.
**https://github.com/aaaamirabbas/nekoray-macos/releases**
If there was a problem, create an issue in the itself repository.

**Comment by Stevemoretz** [comment]
> > > **I have developed a bash script to ‍‍‍‍`automatically` generate a `macOS` version.** **- https://github.com/aaaamirabbas/nekoray-macos**
> > > **In this repository, you can use scripts to build on your system automatically and use pre-made releases for macOS.**
> > > 
> > > * Report if you have any problems.
> > > * Please help contribute and improve this script.
> > > * This script is completely automatic and performs the download and builds operations automatically and finally outputs two applications for different processor architectures.
> > 
> > 
> > Excellent. Does it handle the problem mentioned in the Missing libraries of QT mentioned here?: [#350 (comment)](https://github.com/MatsuriDayo/nekoray/issues/350#issuecomment-1452275076)
> > @arm64v8a The MacOS build document does not say anything about that either. The app does not start if we don't have qt installed on our system. There should be a document to put qt dependencies within build files.
> 
> I examined the QT problem and **solved** it before. In fact, the required QT libraries in this script are attached to the output app.
> 
> You can get and test the latest released version. **https://github.com/aaaamirabbas/nekoray-macos/releases** If there was a problem, create an issue in the itself repository.

I forked that repo, wrote a github action for it which builds the latest version every night, my latest changes aren't yet accepted as a PR in that repo but for anyone in a hurry it is available in my fork:
https://github.com/Stevemoretz/nekoray-macos/releases

<img width="913" alt="Screen Shot 1402-01-29 at 16 53 07" src="https://user-images.githubusercontent.com/27680142/232793427-6b485daa-2f67-4371-ae89-fd3d2e261f8d.png">

**Comment by amirhakimnejad** [comment]
@Stevemoretz @aaaamirabbas Awesome, guys. We can open a pull request on the main repo, too and complete nekoray pipeline to deploy it for all users with the help of @arm64v8a .

**Comment by aaaamirabbas** [comment]
Hi @amirhakimnejad
@arm64v8a does not want to support the macOS version.
Having a version of macOS in the main repository makes users expect fixes (because it has a lot of problems), but @arm64v8a doesn't want to work on fixing these problems.

The script I wrote only makes releases for macOS (but doesn't fix problems).
But in any case, if @arm64v8a agrees, I will prepare the project for pull request.

**Comment by NightMachinery** [comment]
> Hi @amirhakimnejad @arm64v8a does not want to support the macOS version. Having a version of macOS in the main repository makes users expect fixes (because it has a lot of problems), but @arm64v8a doesn't want to work on fixing these problems.
> 
> The script I wrote only makes releases for macOS (but doesn't fix problems). But in any case, if @arm64v8a agrees, I will prepare the project for pull request.

What issues are there? I just tested the build linked in the first comment; it works great. Even the VPN mode works. It's much better than qv2ray, which I was using previously.

**Comment by amirhakimnejad** [comment]
@Stevemoretz @aaaamirabbas Can you guys do a favor and build a newer version for macOS?

**Comment by moretztatlari** [comment]
> @Stevemoretz @aaaamirabbas Can you guys do a favor and build a newer version for macOS?

The build script is broken CI is fine.

@aaaamirabbas Could you take a look at your build script last time I saw it, it had build errors.

**Comment by aaaamirabbas** [comment]
@amirhakimnejad 
I am aware that the script is not compatible with the new changes, but life is hard, and I don't have enough time to adapt right now.
I will do this as soon as possible (although I hope other developers will contribute to the development of this script and make compatibility).

So wait for now until I get the desired time.

**Comment by Nodewebzsz** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nekoray [39043]
Path:                  /Applications/nekoray.app/Contents/MacOS/nekoray
Identifier:            moe.nekoray.macosx
Version:                ()
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-05-23 18:37:01.9184 +0800
OS Version:            macOS 13.3.1 (22E261)
Report Version:        12
Anonymous UUID:        F957214E-3CD8-CC1B-E617-ACC7C9AA9AE1

Sleep/Wake UUID:       3F94B0F7-9885-439B-9BDF-24261F327FE9

Time Awake Since Boot: 170000 seconds
Time Since Wake:       7674 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork
Referenced from: <D2ED90E3-1AD0-3A11-B787-8B2B2B101AC1> /Applications/nekoray.app/Contents/MacOS/nekoray
Reason: tried: '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/usr/local/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff80757fc42 __abort_with_payload + 10
1   dyld                          	    0x7ff807599fd7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff80759a009 abort_with_payload + 9
3   dyld                          	    0x7ff80751e8f0 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff80751bb71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
5   dyld                          	    0x7ff80751a3bd start + 1805


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b914f538  rdx: 0x00007ff7b914f9a0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b914f580  rsp: 0x00007ff7b914f538
   r8: 0x00007ff7b914f5a0   r9: 0x0000000000000000  r10: 0x0000000000000086  r11: 0x0000000000000246
  r12: 0x0000000000000086  r13: 0x00007ff7b914f9a0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff80757fc42  rfl: 0x0000000000000246  cr2: 0x00000001073a5000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x106daf000 -        0x107206fff moe.nekoray.macosx (*) <d2ed90e3-1ad0-3a11-b787-8b2b2b101ac1> /Applications/nekoray.app/Contents/MacOS/nekoray
    0x7ff807514000 -     0x7ff8075ac5a7 dyld (*) <f22a1143-9732-3e23-a8b7-cbade6bb8301> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=176.8M resident=0K(0%) swapped_out_or_unallocated=176.8M(100%)
Writable regions: Total=8468K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8468K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                              43K        3 
__DATA_CONST                       116K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       171.9M        3 
__TEXT                            5060K        2 
dyld private memory                260K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            241.3M       18 



-----------
Full Report
-----------

{"app_name":"nekoray","timestamp":"2023-05-23 18:37:01.00 +0800","app_version":"","slice_uuid":"d2ed90e3-1ad0-3a11-b787-8b2b2b101ac1","build_version":"","platform":1,"bundleID":"moe.nekoray.macosx","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.3.1 (22E261)","roots_installed":0,"name":"nekoray","incident_id":"8D7B9E23-CE5F-4D38-B247-E66F0BB58A75"}
{
  "uptime" : 170000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro14,1",
  "coalitionID" : 11394,
  "osVersion" : {
    "train" : "macOS 13.3.1",
    "build" : "22E261",
    "releaseType" : "User"
  },
  "captureTime" : "2023-05-23 18:37:01.9184 +0800",
  "incident" : "8D7B9E23-CE5F-4D38-B247-E66F0BB58A75",
  "pid" : 39043,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-05-23 18:37:01.8948 +0800",
  "procStartAbsTime" : 176376933117709,
  "procExitAbsTime" : 176376955365061,
  "procName" : "nekoray",
  "procPath" : "\/Applications\/nekoray.app\/Contents\/MacOS\/nekoray",
  "bundleInfo" : {"CFBundleShortVersionString":"","CFBundleVersion":"","CFBundleIdentifier":"moe.nekoray.macosx"},
  "storeInfo" : {"deviceIdentifierForVendor":"06FE6654-CB2A-5D93-B5D9-19786ADBF8D4","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "moe.nekoray.macosx",
  "crashReporterKey" : "F957214E-3CD8-CC1B-E617-ACC7C9AA9AE1",
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 7674,
  "sleepWakeUUID" : "3F94B0F7-9885-439B-9BDF-24261F327FE9",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/usr\/local\/opt\/qt@5\/lib\/QtNetwork.framework\/Versions\/5\/QtNetwork","Referenced from: <D2ED90E3-1AD0-3A11-B787-8B2B2B101AC1> \/Applications\/nekoray.app\/Contents\/MacOS\/nekoray","Reason: tried: '\/usr\/local\/opt\/qt@5\/lib\/QtNetwork.framework\/Versions\/5\/QtNetwork' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/local\/opt\/qt@5\/lib\/QtNetwork.framework\/Versions\/5\/QtNetwork' (no such file), '\/usr\/local\/opt\/qt@5\/lib\/QtNetwork.framework\/Versions\/5\/QtNetwork' (no such file), '\/Library\/Frameworks\/QtNetwork.framework\/Versions\/5\/QtNetwork' (no such file), '\/System\/Library\/Frameworks\/QtNetwork.framework\/Versions\/5\/QtNetwork' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1856350,"threadState":{"r13":{"value":140701938809248},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701938808224},"cr2":{"value":4416229376},"rdx":{"value":140701938809248},"r10":{"value":134},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703251823682,"matchesCrashFrame":1},"rbp":{"value":140701938808192},"rsp":{"value":140701938808120},"r12":{"value":134},"rcx":{"value":140701938808120},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":441410,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":1},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":1},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4409978880,
    "CFBundleShortVersionString" : "",
    "CFBundleIdentifier" : "moe.nekoray.macosx",
    "size" : 4554752,
    "uuid" : "d2ed90e3-1ad0-3a11-b787-8b2b2b101ac1",
    "path" : "\/Applications\/nekoray.app\/Contents\/MacOS\/nekoray",
    "name" : "nekoray",
    "CFBundleVersion" : ""
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703251382272,
    "size" : 624040,
    "uuid" : "f22a1143-9732-3e23-a8b7-cbade6bb8301",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703250759680,
  "size" : 21474836480,
  "uuid" : "1b64bf32-be7f-304b-add0-ce61655e2402"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=176.8M resident=0K(0%) swapped_out_or_unallocated=176.8M(100%)\nWritable regions: Total=8468K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8468K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                              43K        3 \n__DATA_CONST                       116K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       171.9M        3 \n__TEXT                            5060K        2 \ndyld private memory                260K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            241.3M       18 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "dc7ddc9597496d38e1f2f17b050d4eef13ca58f9",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000276
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro14,1, BootROM 509.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.3 GHz, 16 GB, SMC 2.43f11
Graphics: Intel Iris Plus Graphics 640, Intel Iris Plus Graphics 640, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1771)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB30Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.5
there is something wrong with my mac, help me what happened

**Comment by Stevemoretz** [comment]
> @Stevemoretz @aaaamirabbas Can you guys do a favor and build a newer version for macOS?

I only wrote the CI part, he has a problem in his build script, in the meantime we better support and use :

https://github.com/tdjnodj/nekoray

Make sure to give him a star and thank him he deserves it.

**Comment by amirhakimnejad** [comment]
> > @Stevemoretz @aaaamirabbas Can you guys do a favor and build a newer version for macOS?
> 
> I only wrote the CI part, he has a problem in his build script, in the meantime we better support and use :
> 
> https://github.com/tdjnodj/nekoray
> 
> Make sure to give him a star and thank him he deserves it.

Oh, awesome. Just added it to the first message, too

**Comment by Stevemoretz** [comment]
> > > @Stevemoretz @aaaamirabbas Can you guys do a favor and build a newer version for macOS?
> > 
> > 
> > I only wrote the CI part, he has a problem in his build script, in the meantime we better support and use :
> > https://github.com/tdjnodj/nekoray
> > Make sure to give him a star and thank him he deserves it.
> 
> Oh, awesome. Just added it to the first message, too

Great, also added support for 10.15 back: https://github.com/naverMeet/nekoray/pull/41
PR is not accepted yet, in the meanwhile everyone is welcome to download the latest release with MacOS Catalina (10.15) support on my fork: https://github.com/Stevemoretz/nekoray/releases/

**Comment by narakai** [comment]
@NeetHuang  https://github.com/NeetHuang/nekoray-macos-build/releases/ this repo seems not available now

**Comment by amirhakimnejad** [comment]
Mentioned new fork on the first post. https://github.com/Mahdi-zarei/nekoray/
